import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Treasure Hunt",
  description: "Generated by Coding Club NITG",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <link rel="icon" href="/favicon.ico" sizes="any" />



    </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
